### ISSUE TITLE
请问你是用的哪些搜狗词库构建的呀？

### ISSUE THREAD

**Issue by lyjdwh** [CHN-beta/sougou-dict#1]
如题你是用的哪些搜狗词库构建了本词典呀 https://pinyin.sogou.com/dict/

fcitx5-pinyin-sougou aur 包已经被删除了，有考虑更新该包么？

**Comment by CHN-beta** [comment]
> 如题你是用的哪些搜狗词库构建了本词典呀 https://pinyin.sogou.com/dict/
> 
> fcitx5-pinyin-sougou aur 包已经被删除了，有考虑更新该包么？

我忘了用了哪些词库了……大概就是我提交仓库时，存在的所有搜狗词库。

我后来不用arch了，所以就没有维护软件包了。后来大概就被删了，大概。

**Comment by lyjdwh** [comment]
不知道你当初的构建脚本还在不，在的话可以分享下么

**Comment by CHN-beta** [comment]
> 不知道你当初的构建脚本还在不，在的话可以分享下么

https://github.com/StuPeter/Sougou_dict_spider

**Comment by lyjdwh** [comment]
感谢，我更新了下他的代码，https://github.com/lyjdwh/Sougou_dict_spider
